### ISSUE TITLE
Improvements to connectivity widget documentation

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.docs#32]
@borismarin -- I'm reading the [connectivity widget docs](http://docs.geppetto.org/en/latest/connectivityW.html) and I'm trying to figure out how to help make it more accessible.  One confusion I have is that there is little explaining how the "data" which you pass into "setData" comes about.  It is probably second nature to you, but for the average reader, they will have no idea.  

The examples given assume that "cerebellum" and "acnet2" are loaded / exist.  What can we add to explain either why those data sets are mapped by default, or how they come to get mapped in the first place?  

And could we find a way to point to a basic tutorial on "loading data" -- maybe simple data that isn't a huge hairy set of neuroml files but like a "hello world" data file that could be written out in the fewest number of lines?  Then we could link out to that from this widget page (and any other) if folks want to get a feeling for what it means to load data up (even if they use the pre-cooked example data sets).

Thanks!

**Comment by borismarin** [comment]
@slarson acnet2, cerebellum are just the toplevel object for the loaded model - it is probably second nature to @tarelli, @adrianq @gidili ("all" the geppetto "old time" users) as well, because mostly everything we ever do in geppetto involves operating over those objects. There is no additional loading needed, after you are inside a geppetto project (how to create one is an entirely different problem, maybe @tarelli can point us to the relevant docs?).

**Comment by slarson** [comment]
@borismarin thanks for the answer.  yes-- exactly -- because those loaded models are second nature for everybody, I understand how the docs aren't super focused on how to bring in new ones -- but, like for me thinking about c302, I want to better understand how I could go load it up myself potentially, so I'm curious about the next level deeper about how to create a new one.

I expect other outside users coming to Geppetto for the first time will have the same question.

**Comment by tarelli** [comment]
@slarson thanks for the PR! The widgets link ended up buried after we chopped off some obsolete stuff. There's still loads to improve now on the docs, considering also the stuff we've added, see https://github.com/openworm/org.geppetto.docs/issues/25.
As for the how to "load data" the documentation is not focused on that because in that regard Geppetto is meant to be a platform integrated with data/model repos rather than covering the full life cycle. I have on my list to add description of the model schema and how to create/modify a model it will be meant for developers (which files to create, where to put them, all manual stuff, no fancy UI). The real end user will be using Geppetto through other systems (say OSB for NeuroML, WormSim for all OpenWorm or Virtual Fly Brain for drosophila data) and they each have their own ways to create the projects based on their internals. What is in common with all of them is that ones a given model/dataset is loaded the "top level" objects are listed pressing Ctrl+Space as of release 0.2.8

![screen shot 2016-02-21 at 11 48 30](https://cloud.githubusercontent.com/assets/81127/13202399/0f36df66-d891-11e5-8fbd-777a20f2021c.png)

**Comment by borismarin** [comment]
@slarson sure, I agree with you about being as clear as possible - but your
specific question pertains more to "how to create a geppetto project", and
would fit better somewhere else (which objects get created / how to
interact with them will apply to any widget, not only the connectivity
widget?)

**Comment by borismarin** [comment]
It is also fundamental to update the conn. widget docs wrt the new geppetto abstractions (which emerged from the instance/type refactoring™). I started doing that locally, but will wait until there are docs (@tarelli) detailing the new model so we can link to those. The good news: having types makes it much easier to do nice things with the conn. widg, whose customisations mostly concern grouping entities (now   called instances) into categories.

**Comment by tarelli** [comment]
@borismarin https://github.com/openworm/org.geppetto.docs/blob/master/source/geppettomodel.rst I'd point at this.

**Comment by mattearnshaw** [comment]
updated via https://github.com/openworm/org.geppetto.docs/pull/46
