### ISSUE TITLE
Improve documentation at different levels

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.docs#43]
@mattearnshaw 
- [X] Connectivity widget documentation
- [ ] Walkthrough on how to customise Geppetto to build something like OSB? Blog post?

@adrianq 
- [x] Docs: How to extend Geppetto
- [X] Docs: How to configure Geppetto
- [X] Docs: How to theme Geppetto

@Robbie1977 
- [ ] Docs: Stack viewer
- [ ] Walkthrough on how VFB uses Geppetto?Blog post?

@jrmartin 
- [x] Docs: Update Plotting widget
- [x] Docs: Update Experiments table documentation
- [x] Docs for dev: How to add casper tests

@tarelli
- [x] Docs: Better narrative
- [x] Improve Eclipse documentation, remove old stuff, make it one coherent flow/ Remove Blue Pill/Red Pill?
- [X] [Attempt converting RST to MD?](https://github.com/openworm/org.geppetto.docs/issues/41)
- [x] Edit docs link
- [X] Improve narrative

**Comment by LordKrabo** [comment]
I'll improve the installation part of the documentation.

**Comment by adrianq** [comment]
@LordKrabo I had to format my laptop with a fresh new Ubuntu (16.04). These are some notes I made while reinstalling Geppetto from scratch. I guess this would be Geppetto Development installation notes or sth like that. For a non-developer user, installation should be more straight-forward using the scripts. Anyway, in case that it helps, here they are:

- Download latest Eclipse. In order to write these notes Eclipse Oxygen (4.7.0) was used.
- Install virgo tooling in Eclipse. You can find some info here under Install Virgo section (https://wiki.eclipse.org/Virgo/Tooling). Use this repository to download Virgo tooling http://download.eclipse.org/virgo/release/tooling/ (Field 'Work with')
- Download Virgo Server from here https://eclipse.org/virgo/download/. For now, go for version 3.6.4.
- Clone org.geppetto (https://github.com/openworm/org.geppetto).
- Configure in org.geppetto/utilities/source_setup/config.json and org.geppetto/pom.xml the Geppetto bundles you will be working with. For a basic installation, we recommend the following bundles: org.geppetto.frontend, org.geppetto.core, org.geppetto.simulation, org.geppetto.model and org.geppetto.model.neuroml.
- Clone each of these repos. Repos should be cloned at the same level than org.geppetto (probably there is a tool to perform this action in a more automatic way).
- Import Projects in Eclipse. An approach to do this can be: 
   - Add Git View: Windows > Show View > Git Repositories
   - Click on 'Add an existing local Git repository to this view' and add all the cloned project (including org.geppetto) to the Eclipse IDE.
   - Right click on them and choose 'Import Projects'
- Right click on org.geppetto > Run As > mvn install
- If the previous step run successfully, we now need to copy the libs to Vrgo. Go back to the shell and execute in org.geppetto/utilities/source_setup python update_server.py eclipse. This will copy all the libs for you to the Virgo Server. In this folder you can find some other interesting scripts for instance you can use gitall to perform bulk git operations on your bundles (pull, branch, checkout, etc)
- Finally, we need to configure the Virgo Tooling. In the 'Servers' tab in Eclipse, click on add a new Server, choose 'Virgo Runtime' and select the folder where you have installed the Virgo Server. Add all the bundles to the Virgo tooling (either during the creation process or by right-clicking on the just created server and choosing 'Add and Remove'). Tip: If any of the bundle doesn't show up as an available bundle right click on the project and click on Virgo > Add OSGi Bundle Project Nature
- Start the server and go to localhost:8080

**Comment by LordKrabo** [comment]
Absolutely @adrianq ! I'll rewrite the install documents this afternoon.

**Comment by tarelli** [comment]
@LordKrabo I ended up reworking the Eclipse docs today along with a few other sections

**Comment by tarelli** [comment]
@mattearnshaw that tutorial would be very useful, do you still plan to work on it? @Robbie1977 will you have some time for the documentation?

**Comment by mattearnshaw** [comment]
@tarelli yeah, can start on it week after next

**Comment by LordKrabo** [comment]
I'm sorry for going silent @tarelli. Been bogged down with other work. Is there anything I can still help with on the documentation?

**Comment by Robbie1977** [comment]
@tarelli depressingly won’t have any time to look at this for about a
month.
